### ISSUE TITLE
Write README.md

### ISSUE THREAD

**Issue by TanushJadhav** [TanushJadhav/OST--Urban-Land-Cover#1]
We need someone to write us the README.md file, that showcases everything that has been done in our project. Kindly let us know if you are interested and we will brief you what to write.

**Comment by mademoiselle-chantal** [comment]
Hello, @TanushJadhav. Can I work on this issue?

**Comment by TanushJadhav** [comment]
Definitely you can do so

**Comment by TanushJadhav** [comment]
> Hello, @TanushJadhav. Can I work on this issue?

Definitely, you can surely do so!

**Comment by mademoiselle-chantal** [comment]
> > Hello, @TanushJadhav. Can I work on this issue?
> 
> Definitely, You can surely do so!

Thanks! Can you kindly brief me on what l should write?

**Comment by TanushJadhav** [comment]
> > > Hello, @TanushJadhav. Can I work on this issue?
> > 
> > 
> > Definitely, You can surely do so!
> 
> Thanks! Can you kindly brief me on what l should write?

Surely!

If you visit the AI MODEL directory in the repository, you will find a file named Urban_Land_Cover.ipynb, This file contains all the models that have been used. Out of all the models, we have used Random Forest Classifier to classify land covers.

Basically, what we expect is some write-up about the dataset (link for dataset: https://archive.ics.uci.edu/dataset/295/urban+land+cover). Also, we would like some write-up about the AI Model/random forest classifier used.  Also, mention that the accuracy of the random forest classifier algorithm is 91.38%.

If u need any assistance, you can refer to this paper - https://ieeexplore.ieee.org/document/10461930

Also, if possible, could you try to complete it as soon as possible, since it is a bit urgent. Thanks a lot.
